spring.application.name=testSpring
spring.data.mongodb.uri=mongodb://localhost:27017/equipdb
spring.data.mongodb.auto-index-creation=true
spring.jackson.default-property-inclusion=non_null
server.address=0.0.0.0
