spring.application.name=TKStorrageBack
spring.data.mongodb.uri=mongodb://localhost:27017/equipdb
spring.data.mongodb.auto-index-creation=true
spring.jackson.default-property-inclusion=non_null
server.address=0.0.0.0
appscript.export.url=https://script.google.com/macros/s/AKfycbzNzt9rsGcj6YR1ak95775_6_q9Z1FJQJfBt15x_BpVqFQbtOFN8XwVNyjdgx-tzFrOdA/exec
